### PR TITLE
Swift 4

### PR DESCRIPTION
**Pull request by andrewreeman**
Updated to swift 4. Needed to modify some flat maps in the multiselection logic.
Untested

### CODE REVIEW

**Comment by noais** [comment]
This is working?

**Comment by noais** [comment]
<div class="tenor-gif-embed" data-postid="8138721" data-share-method="host" data-width="100%" data-aspect-ratio="1.7785714285714287"><a href="https://tenor.com/view/bravo-gif-8138721">Bravo Applause GIF</a> from <a href="https://tenor.com/search/bravo-gifs">Bravo GIFs</a></div><script type="text/javascript" async src="https://tenor.com/embed.js"></script>

**Comment by andrewreeman** [comment]
Just tested this now using the demo and it seems to work fine. Perhaps there could be some unit tests or a testing methodology for future merges? :)

Thanks!

**Comment by getSwiftly** [comment]
Maybe updating the ReadMe to show that swift 4 is compatible. Also the swift 4 support issue closed please.

**Comment by jerrypm** [comment]
how to use this dropdown for restAPI

**Comment by getSwiftly** [comment]
Use closure and callback for the API call to populate the data source for the dropdown and use the main thread async dispatch queue for populating the data source array and calling the function on to show the dropdown menu.

**Pull request closed without merging**
