### PR TITLE
Updated Swift 4

### PR DESCRIPTION
**Pull request by aashishtamsya**

### CODE REVIEW

**Comment by mickychen0524** [comment]
@aashishtamsya can I use your branch for swift 4 support? or it must be merged before?

**Comment by aashishtamsya** [comment]
Yes @mickychen0524 you can use that.

**Comment by mickychen0524** [comment]
@aashishtamsya can you provide the url?

**Comment by saormart** [comment]
Hello I also need it for Swift 4 ... can you provide the link for your branch or some one could merge this ? Thanks !

**Comment by aashishtamsya** [comment]
[Link to the branch](https://github.com/aashishtamsya/DropDown/tree/swift-4)

**Comment by kevin-hirsch** [comment]
Thanks a lot for working on Swift 4 support! 🙏 
Swift 4 support has been already merged with #118 😉

**Pull request closed without merging**
