### PR TITLE
Swift 4.2 support

### PR DESCRIPTION
**Pull request by chlumik**
Simple change to support Swift 4.2

### CODE REVIEW

**Comment by Mordil** [comment]
This will resolve #190

**Comment by kevin-hirsch** [comment]
Hello @chlumik 👋 

Thanks a lot for this PR 🙏
It's now merged. I've created a new version 2.3.3 available via CocoaPods and Carthage 🚀

**Comment by chlumik** [comment]
@kevin-hirsch You're welcome.

**Comment by saormart** [comment]
@22Round, have you tried to configure the framework for the 4.2 version?
screen shot 2018-09-24 at 9 29 59 am

**Comment by kevin-hirsch** [comment]
Hello @22Round 👋 

I forgot to update the `.swift-version` file that CocoaPods uses to determine the Swift version that the project uses (which still was 4.0)

It should now work if you try using the latest version DropDown v2.3.4 🎉

Thanks for noticing 🙏

**Comment by 22Round** [comment]
@kevin-hirsch @saormart Thanks, I updated pod and it compiles
only one warning remained, please fix it ;)

screen shot 2018-09-25 at 11 58 24

**Comment by iwb-kevin-hirsch** [comment]
Hey @22Round,

It's done and available in version 2.3.5 😉

**Comment by kevin-hirsch** [comment]
Hey @22Round,

It's done and available in version 2.3.5 😉

**Pull request merged**
