### PR TITLE
Fixed crash when import using SPM

### PR DESCRIPTION
**Pull request by balavor**
# Issue #280

## Description
- Added correct bundle when using Swift Package Manager
- Fixed module target in `.xib` file
- Updated build tools and explicitly specified resources folder

### CODE REVIEW

**Comment by RomanTysiachnik** [comment]
@kevin-hirsch

**Comment by Jeehut** [comment]
Would be great to see this getting merged. 👍 
It also fixes this issue with Xcode 12.4: https://bugs.swift.org/browse/SR-13579

**Comment by kevin-hirsch** [comment]
Here you go 🙂

**Review by KidiIT — COMMENTED** [review]
All reviewed and approved🫶❤️🙂

**Comment by KidiIT** [comment]
All reviewed and successfully approved🤓❤️

**Pull request merged**
