### PR TITLE
Swift 4.0 support

### PR DESCRIPTION
**Pull request by pskow**
Hi!
I converted project to swift-4.0.

### CODE REVIEW

**Comment by Ethandf90** [comment]
someone please merge to support swift4

**Comment by saormart** [comment]
I also need it for Swift 4 ! @pskow can you provide your branch link that suports swift 4 ?
Or may some one could merge it to suport swift 4 !
Thanks !

**Comment by pskow** [comment]
@Alexookah is it possible to merge it ? thanks!

**Comment by Alexookah** [comment]
sorry i am not able to merge any settings in this repo. i just checked the code and marked these changes to be merged maybe from the repository owner or so.

**Comment by pskow** [comment]
@kevin-hirsch is it possible to merge it for suport swift 4.0 ?

**Comment by kevin-hirsch** [comment]
Thanks a lot for this PR! 💯 
It's merged ✅

**Pull request merged**
